SCORER_MAX_MEMORY_CHARS: int = 2000
CHROMA_DOC_MAX_CHARS: int = 500

EMBEDDER_MAX_TEXT_CHARS: int = 2048

CONSUMER_TASK_MAX_CHARS: int = 300

PUBLISHER_TOPIC_MAX_CHARS: int = 200

LOG_PREVIEW_CHARS: int = 80